<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" />
    <PackageReference Include="H.NotifyIcon.Wpf" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TitaniRun.Ipc.Client\TitaniRun.Ipc.Client.csproj" />
    <ProjectReference Include="..\TitaniRun.Ipc.Contracts\TitaniRun.Ipc.Contracts.csproj" />
  </ItemGroup>

</Project>
